# .air.toml
root = "./"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/budget-server ./cmd/budget-server/ 2> ./tmp/build-errors.log"
  bin = "./tmp/budget-server"
  # Include all files ending with `.go` and all directories
  include = [
    "*.go",
    "./cmd/**/*.go",
    "./internal/**/*.go",
    "./configs/**/*.go",
  ]
  # Exclude the tmp directory
  exclude = ["tmp"]

[log]
  # Log file name
  file = "air_errors.log"

[color]
  # Enable colors in the output
  main = "yellow"
  watcher = "green"
  build = "blue"

[serve]
  # This section is about running the program
  # Command to start the server
  cmd = "./tmp/budget-server"
  # Environment variables
  env = ["PORT=3000", "DB_HOST=db"]
  # Port forwarding from container to host
  port = "3000"
  # Delay before restarting the build after file changes
  delay = "1000ms"  # 1 second
