version: '3.8'
services:
  db:
    env_file:
      - configs/dev.env
    ports:
      - "3306:3306"
    build:
      context: .
      dockerfile: configs/db.Dockerfile
    volumes:
      - budget_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: configs/web.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - configs/dev.env
    depends_on:
      - db
volumes:
  budget_data:
    driver: local