version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: configs/web.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - configs/dev.env
    volumes:
      - .:/app
    depends_on:
      - db